name: Trabalho de hoje 
 
on: 
  push:
    branche: [ main ]
 
jobs: 
  build-e-faze-teste:
    runs-on: ubuntu-latest
 
 
steps:
-   name: 1. Pegue o caderno
    uses: actions/checkout@v3
 
-   name: 2. Vendo que esta escrito
    run: echo "analisando caderno"
 
-   name: 3. Conclução do caderno
    run: echo "Caderno completo"
